name: Run tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.6', '3.7', '3.8' ]
    name: Run tests
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: make init
      - name: Lint
        run: make check
        if: matrix.python-version == '3.6'
      - name: Build docs
        run: make doc
        if: matrix.python-version == '3.6'
      - name: Run doctests
        run: make doctest
      - name: Run tests
        run: make coverage
      - name: Upload coverage
        run: coveralls
        if: matrix.python-version == '3.6'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_SERVICE_NAME: github
